"""Add performance indexes

Revision ID: 1b0f83b6d5d7
Revises: 8ae777020816
Create Date: 2026-04-14 15:38:05.270359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b0f83b6d5d7'
down_revision: Union[str, Sequence[str], None] = '8ae777020816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badges', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('chat_memories', 'session_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('chat_memories', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('idx_chat_memories_session_id'), table_name='chat_memories')
    op.drop_index(op.f('idx_chat_memories_user_created'), table_name='chat_memories')
    op.create_index(op.f('ix_chat_memories_session_id'), 'chat_memories', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_memories_user_id'), 'chat_memories', ['user_id'], unique=False)
    op.alter_column('goals', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_goals_user_id'), table_name='goals')
    op.drop_index(op.f('idx_goals_user_status'), table_name='goals')
    op.create_index(op.f('ix_goals_status'), 'goals', ['status'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.drop_table_comment(
        'goals',
        existing_comment='User goals across domains (learning, fitness, startup, etc.)',
        schema=None
    )
    op.drop_index(op.f('idx_milestones_goal_id'), table_name='milestones')
    op.create_index(op.f('ix_milestones_goal_id'), 'milestones', ['goal_id'], unique=False)
    op.drop_table_comment(
        'milestones',
        existing_comment='Ordered checkpoints within a goal',
        schema=None
    )
    op.alter_column('notifications', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('tasks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_tasks_milestone_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_completed_at'), 'tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_tasks_milestone_id'), 'tasks', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.drop_table_comment(
        'tasks',
        existing_comment='Individual actionable items within a milestone',
        schema=None
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.drop_table_comment(
        'users',
        existing_comment='Application user profiles linked to Supabase Auth',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Application user profiles linked to Supabase Auth',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.create_table_comment(
        'tasks',
        'Individual actionable items within a milestone',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_milestone_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed_at'), table_name='tasks')
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['milestone_id', 'status'], unique=False)
    op.create_index(op.f('idx_tasks_milestone_id'), 'tasks', ['milestone_id'], unique=False)
    op.alter_column('tasks', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.alter_column('notifications', 'type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table_comment(
        'milestones',
        'Ordered checkpoints within a goal',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_milestones_goal_id'), table_name='milestones')
    op.create_index(op.f('idx_milestones_goal_id'), 'milestones', ['goal_id'], unique=False)
    op.create_table_comment(
        'goals',
        'User goals across domains (learning, fitness, startup, etc.)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_status'), table_name='goals')
    op.create_index(op.f('idx_goals_user_status'), 'goals', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.alter_column('goals', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_chat_memories_user_id'), table_name='chat_memories')
    op.drop_index(op.f('ix_chat_memories_session_id'), table_name='chat_memories')
    op.create_index(op.f('idx_chat_memories_user_created'), 'chat_memories', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_chat_memories_session_id'), 'chat_memories', ['session_id'], unique=False)
    op.alter_column('chat_memories', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_memories', 'session_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('badges', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
