"""Add GDI and Session telemetry

Revision ID: 7839e489928b
Revises: 1b0f83b6d5d7
Create Date: 2026-04-14 23:47:25.663993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7839e489928b'
down_revision: Union[str, Sequence[str], None] = '1b0f83b6d5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_signal_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('reward_value', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_signal_logs_timestamp'), 'reward_signal_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_reward_signal_logs_user_id'), 'reward_signal_logs', ['user_id'], unique=False)
    op.create_table('user_behavior_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('momentum_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('avoidance_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('decay_value', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('gdi_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_behavior_logs_date'), 'user_behavior_logs', ['date'], unique=False)
    op.create_index(op.f('ix_user_behavior_logs_user_id'), 'user_behavior_logs', ['user_id'], unique=False)
    op.create_table('user_session_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tasks_completed_in_session', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_session_logs_login_timestamp'), 'user_session_logs', ['login_timestamp'], unique=False)
    op.create_index(op.f('ix_user_session_logs_user_id'), 'user_session_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_logs_user_id'), table_name='user_session_logs')
    op.drop_index(op.f('ix_user_session_logs_login_timestamp'), table_name='user_session_logs')
    op.drop_table('user_session_logs')
    op.drop_index(op.f('ix_user_behavior_logs_user_id'), table_name='user_behavior_logs')
    op.drop_index(op.f('ix_user_behavior_logs_date'), table_name='user_behavior_logs')
    op.drop_table('user_behavior_logs')
    op.drop_index(op.f('ix_reward_signal_logs_user_id'), table_name='reward_signal_logs')
    op.drop_index(op.f('ix_reward_signal_logs_timestamp'), table_name='reward_signal_logs')
    op.drop_table('reward_signal_logs')
    # ### end Alembic commands ###
